### PR TITLE
Self sign APK

### PR DESCRIPTION
**Pull request by mche3kek**
Release APK creation, self signed and ready to be used

### CODE REVIEW

**Comment by mche3kek** [comment]
I had a bit of trouble setting up the keystore credentials and getting it to work locally

**Comment by mche3kek** [comment]
Signing the app changed nothing, I just re-uploaded the google-services.json to the secrets in case we modified some setting in Firebase without reflecting it on the secrets item

**Comment by mche3kek** [comment]
It seems we forgot to register the SHA key of the release version in the app, now everything seems fixed !

**Review by FacerOfGod — COMMENTED** [review]
The goal of this pull request is to automate the process of creating a release APK for the app. The sensitive data is well managed. Maybe we should document/comment `apk.yml` for better understanding if someone wants to modifiy it later on, what do you think ? I tested and it works, ready to merge. Nice job !

**Comment by mche3kek** [comment]
> The goal of this pull request is to automate the process of creating a release APK for the app. The sensitive data is well managed. Maybe we should document/comment apk.yml for better understanding if someone wants to modifiy it later on, what do you think ? I tested and it works, ready to merge. Nice job !

Sorry haven't seen your review, will try to document some more and I'll let you know !

**Comment by mche3kek** [comment]
> The goal of this pull request is to automate the process of creating a release APK for the app. The sensitive data is well managed. Maybe we should document/comment apk.yml for better understanding if someone wants to modifiy it later on, what do you think ? I tested and it works, ready to merge. Nice job !

@FacerOfGod I've added a few comments and clarified some task names with a bit more information so it is easier to understand, but I think there is nothing much to add to make it more clear it seems pretty straightforward what each task is doing and why, let me know if you think something would benefit from more clarification :)

**Pull request merged**
