### PR TITLE
CI fix for Github Actions

### PR DESCRIPTION
**Pull request by mche3kek**
Upload of missing jar file from template project

### CODE REVIEW

**Comment by mche3kek** [comment]
Checks pass but no upload of test coverage, needs more investigating

**Comment by mche3kek** [comment]
Location of Jacoco tests is created well on local machine, don't see where is the problem

**Comment by mche3kek** [comment]
A maj was missing to the folder name 😢

**Comment by fdejean** [comment]
The test of the template do not meet the Code coverage lead to SonarCould Analysis to fail. This will fix it self when implementing other features.

**Review by ohamz — APPROVED** [review]
CI tests / SonarCloud setup completed 
Code coverage is irrelevant for the moment as no UI was implemented yet

**Pull request merged**
