### PR TITLE
BUG FIX : Crash on Start

### PR DESCRIPTION
**Pull request by fdejean**
Weird bug that is not related to recent push but due to the database update.
Landing Page fetch some default recipe but they have been deleted.
The view model was wrongly coded to threw and error if a recipe is not found.
Replaced the threw with a Logging instead.

### CODE REVIEW

**Comment by mche3kek** [comment]
You need to do a KTFMT format :)

**Comment by fdejean** [comment]
The real bug is that the firestore document path name has been changed. Hence, the onFailure is called.

This occured when @0marwa @xrsula uploaded the reciped to the database.
Can you modify the database to have the correct path name ? 
@0marwa @xrsula thanks you :)

**Comment by fdejean** [comment]
Another bug was found :
We exceed our quota extremely quickly with the new filled scraped recipes.
I think this is due to the search bar, as the query get "all the matching criteria" and does not limit the size.
Hence a query with "a" will get all the recipes containing an "a". 
Fix : added a limit close the query of the search bar

**Review by ohamz — APPROVED** [review]
Well done catching these bugs, and implementing safe measures for the moment until we fix them !

**Comment by fdejean** [comment]
Well, the fix of the search was needed, but the thing that exceed our quota is simply 
- Using the firestore webpage make queries. Do not manually look for a recipe and scroll. 
Just loading the firestore /recipes make about 2k request....

**Pull request merged**
