### PR TITLE
Manuel ingredient input

### PR DESCRIPTION
**Pull request by FacerOfGod**
Implement the UI for manual ingredient input with:
- Dropdown menu for ingredient selection with suggestions
- Number input for doses
- Dropdown menu for dose types with suggestions
- Ability to delete ingredients and add multiple ingredients

### CODE REVIEW

**Comment by FacerOfGod** [comment]
Little week 4 update : Coding a sleek UI like we planned in Kotlin turned out to be way tougher than I expected! It took a lot of time just to get it to this point. Right now, it's functional, but gotta admit, I'm not entirely satisfied with how it turned out for now. If I don't tidy it up and make everything clear now, it'll be a pain to fix or use later. I will be working on this for the week 5 as well

- You can add and delete ingredients
- DropdownMenus are functional
- the overall UI has been maded
f we don't tidy it up and make everything clear now, it'll be a pain to fix or use later.
UPDATE

**Review by JeannedeM — CHANGES_REQUESTED** [review]
Hey, seems very, great job for achieving this really complicate feature ;)
Could you add some documentation to help understand what you have done pleaseee?
(or maybe i just don't see your documentation idk ?)

**Comment by FacerOfGod** [comment]
@JeannedeM Documentation for `CreateScreen` was missing and was added. All the other functions have already been documented. Are the changes good ?

**Review by JeannedeM — APPROVED** [review]

**Comment by JeannedeM** [comment]
Yes the code looks fine to me. About the documentation i forgot to pull on your branch and didn't had the lattest version... We will have UI update to do later. Great job thank youuuu !

**Pull request merged**
