### PR TITLE
Fix UI of ingredients input

### PR DESCRIPTION
**Pull request by ohamz**
Fixing the UI for ingredients input, this is what the old UI looks like:

image

What it looks like now:
image

### CODE REVIEW

**Comment by ohamz** [comment]
Draft 1 looks like this:

Screenshot 2024-05-18 151106

**Comment by ohamz** [comment]
Draft 2 looks like this:

image

**Comment by ohamz** [comment]
draft 3 (and final maybe):
image

**Comment by ohamz** [comment]
Ready for review :)

**Review by mche3kek — APPROVED** [review]
Everything looks good to me, great work !

**Review by JeannedeM — APPROVED** [review]
Hey, amazing work the result is so much cleaner !! Just watch this screen makes me happy :D

**Pull request merged**
