### PR TITLE
Fix the UI of following button in Profile Screen

### PR DESCRIPTION
**Pull request by xrsula**
In order to fix the UI of the following button in Profile Screen, I added additional padding to main UI components in order to make the screen fit better any type of phone screen

### CODE REVIEW

**Comment by ohamz** [comment]
@JeannedeM can you test it on your device if it works ? If I remember the problem was when launching the app on a physical device, on the emulator it's fine.

image

**Comment by JeannedeM** [comment]
> @JeannedeM can you test it on your device if it works ? If I remember the problem was when launching the app on a physical device, on the emulator it's fine.
> image

I tried on my phone and it was still the same problem :(
image

**Comment by JeannedeM** [comment]
I just push something that fixes the roblem on my phone, but it would be great of @xrsula  and @ohamz  could test it, to be sure it's not a mess on their phones....

**Comment by ohamz** [comment]
> I just push something that fixes the problem on my phone, but it would be great of @xrsula and @ohamz could test it, to be sure it's not a mess on their phones....

It still works on the emulator so I think the fix is good !

image

**Review by ohamz — APPROVED** [review]
Bug fixed !

**Pull request merged**
