### PR TITLE
SignOut button

### PR DESCRIPTION
**Pull request by ohamz**
Implemented the SignOut button in SettingsScreen and added a main test for display.

### CODE REVIEW

**Comment by ohamz** [comment]
Should I add a test for onClick functionality of SignOut button ? 
I can try but I think it will cause trouble as when we tested the sign in (when it used to fail alot on CI so we removed it).

**Review by xrsula — CHANGES_REQUESTED** [review]
Everything looks good for me ! It would be nice to specify the TODO for the top bar in SettingsScreen.kt to see what you plan on doing for it ! a small comment to describe the contents of it is sufficient

**Comment by ohamz** [comment]
> Everything looks good for me ! It would be nice to specify the TODO for the top bar in SettingsScreen.kt to see what you plan on doing for it ! a small comment to describe the contents of it is sufficient

The UI for the settings screen is left for another issue, that's why I minimalized my part so that this PR focuses on the backend of the button. But I agree it's a good idea to add some comments in order to mark it clear.

**Review by xrsula — APPROVED** [review]
All good :)

**Pull request merged**
