### PR TITLE
Filtering script and filtered ingredients .json are done

### PR DESCRIPTION
**Pull request by xrsula**
This PR deals with the filtering of the ingredients. In the all_ingredients.json, there were ~18'000 lines of unfiltered ingredients. 

In filtering.ipynb, a 3-part script helps to clean up the noise (useless information) around the ingredients, remove duplicates, and sort by alphabetical order.

The first phase was to remove all measurements, numbers, and units around the ingredients. After that, the resulting .json goes through a second phase of filtering. The third phase was to sort through the list (which was narrowed down to ~4'500 lignes) by and to remove lingering noise around the data, alternating between hand-filtering and running a script to sort by alphabetical order and remove redundant ingredients.

### CODE REVIEW

**Review by mche3kek — CHANGES_REQUESTED** [review]
Nice filtering code, ingredients look sorted in alphabetical order. Is it normal to still have duplicate ingredients at this stage ? (e.g : raisins, raisins chopped)

**Comment by xrsula** [comment]
> Nice filtering code, ingredients look sorted in alphabetical order. Is it normal to still have duplicate ingredients at this stage ? (e.g : raisins, raisins chopped)

Not really ^^ some details must have slipped I will fix this asap !

**Comment by mche3kek** [comment]
> > Nice filtering code, ingredients look sorted in alphabetical order. Is it normal to still have duplicate ingredients at this stage ? (e.g : raisins, raisins chopped)
> 
> Not really ^^ some details must have slipped I will fix this asap !

let me know when it's done then !

**Comment by xrsula** [comment]
> > > Nice filtering code, ingredients look sorted in alphabetical order. Is it normal to still have duplicate ingredients at this stage ? (e.g : raisins, raisins chopped)
> > 
> > 
> > Not really ^^ some details must have slipped I will fix this asap !
> 
> let me know when it's done then !

It should be all good now ! I passed one last time though the list and removed several duplicates and noisy info that was left

**Comment by mche3kek** [comment]
> > > > Nice filtering code, ingredients look sorted in alphabetical order. Is it normal to still have duplicate ingredients at this stage ? (e.g : raisins, raisins chopped)
> > > 
> > > 
> > > Not really ^^ some details must have slipped I will fix this asap !
> > 
> > 
> > let me know when it's done then !
> 
> It should be all good now ! I passed one last time though the list and removed several duplicates and noisy info that was left

Data seems way better filtered, all good to me we can iron it out later on if we find other duplicated, good job !

**Review by mche3kek — APPROVED** [review]

**Pull request merged**
